In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [3]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a.shape     # 查看矩阵形状

(2, 4)

In [5]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
d.shape     # 从左到右依次表示一维到高维的元素个数

(2, 2, 3)

In [9]:
d1 = np.array(range(20)).reshape(2,2,5)

In [10]:
d1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [11]:
d1.reshape(4,5)     # 这种方法只是对副本进行更该，原数组并不改变

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
d1 = d1.reshape(4,5)

In [13]:
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
d1.reshape(20,1)        # 一维

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [15]:
d2 = d1.reshape(d1.shape[0] * d1.shape[1],)     # 行数乘以列数为矩阵形状，以此来制作一个一维数组 

In [16]:
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
d1.flatten()    # 按行展开成一维数组

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])