In [11]:
import numpy as np

In [12]:
t1 = np.array(range(1,21))

In [13]:
t1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
t2 = t1.reshape(4,5)

In [15]:
t2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
t2 + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [18]:
t2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [19]:
t2 / 2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ]])

In [20]:
t3 = np.array(range(20))

In [27]:
t3 = t3.reshape(4,5)

In [28]:
t3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
t4 = t2*t3

In [30]:
t4

array([[  0,   2,   6,  12,  20],
       [ 30,  42,  56,  72,  90],
       [110, 132, 156, 182, 210],
       [240, 272, 306, 342, 380]])

In [31]:
t2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
t5 = np.arange(4).reshape(4,1)

In [36]:
t5

array([[0],
       [1],
       [2],
       [3]])

In [37]:
t2 * t5

array([[ 0,  0,  0,  0,  0],
       [ 6,  7,  8,  9, 10],
       [22, 24, 26, 28, 30],
       [48, 51, 54, 57, 60]])

In [38]:
t2 - t5

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17]])

In [39]:
t6 = np.arange(5).reshape(1,5)

In [40]:
t6

array([[0, 1, 2, 3, 4]])

In [41]:
t2 - t6

array([[ 1,  1,  1,  1,  1],
       [ 6,  6,  6,  6,  6],
       [11, 11, 11, 11, 11],
       [16, 16, 16, 16, 16]])