In [4]:
import numpy as np

In [5]:
my_arr = np.array(1000000)

In [6]:
my_list = list(range(1000000))

In [7]:
my_arr

array(1000000)

In [8]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 641 ms
Wall time: 728 ms


可以看出numpy的效率之高

In [11]:
data = np.random.randn(2,3)

In [12]:
data

array([[-0.02925092,  0.20912973,  0.80031907],
       [-0.75613855,  1.04445078,  1.5409807 ]])

In [13]:
data*10

array([[-0.29250921,  2.09129734,  8.00319068],
       [-7.56138547, 10.44450779, 15.40980701]])

In [14]:
data+data

array([[-0.05850184,  0.41825947,  1.60063814],
       [-1.51227709,  2.08890156,  3.0819614 ]])

在NumPy中，np.random.randn函数生成标准正态分布（均值为0，标准差为1）的随机数。因此，生成的随机数的范围在理论上是负无穷到正无穷，但通常情况下，绝大多数随机数会落在-3到3之间，而极少数会落在更远的范围内

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
data1 = [6, 7.5, 8, 0, 1]

In [18]:
arr1 = np.array(data1)

In [19]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
arr1.shape

(5,)

In [21]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [22]:
np.array(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[9.75835752e-312, 2.66795449e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23053953e-307, 1.16095484e-028]],

       [[3.65093134e+233, 8.97600969e-096],
        [1.04918330e-153, 9.78750380e+199],
        [6.97843734e+252, 1.35264518e+165]]])

认为np.empty会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
arr.dtype

dtype('int32')

In [35]:
float_arr = arr.astype(np.float64)

In [36]:
float_arr.dtype

dtype('float64')

In [38]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [39]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

按不足近似保留

In [40]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [41]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [46]:
numeric_strings.dtype

dtype('S4')

In [42]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [43]:
int_array = np.arange(10)

In [44]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
empty_uint32 = np.empty(8, dtype='u4')

In [49]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [50]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [55]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

以上实例表示运算和对比都是一一对应

In [56]:
arr = np.arange(10)

In [57]:
arr[5]

5

In [58]:
arr[5:8]

array([5, 6, 7])

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr_slice = arr[5:8]

In [61]:
arr_slice

array([5, 6, 7])

In [62]:
arr_slice[1] = 12345

In [63]:
arr_slice

array([    5, 12345,     7])

In [0]:
arr_slice[:] = 64

深拷贝，相当于引用传递

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [65]:
arr_slice

array([64, 64, 64])

In [66]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d.shape

(2, 2, 3)

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr3d[0].shape

(2, 3)

In [73]:
old_values = arr3d[0].copy()

In [74]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr3d[0]=42

In [76]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [77]:
arr3d[0]=old_values

In [78]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[1, 0]

8

牛逼，这样访问低维数组

In [82]:
x = arr3d[1]

In [83]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [84]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

前关闭，后打开

In [90]:
arr2d = np.arange(9).reshape(3,3)

In [91]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr2d[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
arr2d[:2, 1:]

array([[1, 2],
       [4, 5]])

In [95]:
arr2d[1, :2]

array([3, 4])

In [96]:
arr2d[:, :1]

array([[0],
       [3],
       [6]])

In [97]:
arr2d[:2, 1:] = 0

In [98]:
arr2d

array([[0, 0, 0],
       [3, 0, 0],
       [6, 7, 8]])

In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [100]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [101]:
data=np.random.randn(7,4)
                     

In [102]:
data

array([[-1.55677115,  0.40926864, -0.66107851,  0.89255626],
       [-0.8201285 ,  0.31174478, -0.67062715,  1.2112391 ],
       [-0.87572477, -1.78773802, -0.78373774, -0.99170176],
       [-0.28251279,  0.74119466, -1.09110507,  1.29168528],
       [-2.12220003, -0.81525569,  0.7411174 , -0.62546329],
       [-1.40391308,  1.2779262 ,  1.68418952,  0.48085237],
       [ 0.577898  , -1.87600216, -1.61084579,  1.88829546]])

In [103]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [104]:
data[names == 'Bob']

array([[-1.55677115,  0.40926864, -0.66107851,  0.89255626],
       [-0.28251279,  0.74119466, -1.09110507,  1.29168528]])

返还值为true的行

In [105]:
data[names == 'Bob', 2:]

array([[-0.66107851,  0.89255626],
       [-1.09110507,  1.29168528]])

In [106]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [107]:
data[~(names == 'Bob')]

array([[-0.8201285 ,  0.31174478, -0.67062715,  1.2112391 ],
       [-0.87572477, -1.78773802, -0.78373774, -0.99170176],
       [-2.12220003, -0.81525569,  0.7411174 , -0.62546329],
       [-1.40391308,  1.2779262 ,  1.68418952,  0.48085237],
       [ 0.577898  , -1.87600216, -1.61084579,  1.88829546]])

In [109]:
cond = names == 'Bob'

In [110]:
data[~cond]

array([[-0.8201285 ,  0.31174478, -0.67062715,  1.2112391 ],
       [-0.87572477, -1.78773802, -0.78373774, -0.99170176],
       [-2.12220003, -0.81525569,  0.7411174 , -0.62546329],
       [-1.40391308,  1.2779262 ,  1.68418952,  0.48085237],
       [ 0.577898  , -1.87600216, -1.61084579,  1.88829546]])

In [111]:
mask = (names == 'Bob') | (names == 'Will')

In [112]:
mask

array([ True, False,  True,  True,  True, False, False])

In [113]:
data[mask]

array([[-1.55677115,  0.40926864, -0.66107851,  0.89255626],
       [-0.87572477, -1.78773802, -0.78373774, -0.99170176],
       [-0.28251279,  0.74119466, -1.09110507,  1.29168528],
       [-2.12220003, -0.81525569,  0.7411174 , -0.62546329]])

In [114]:
data[data < 0] = 0

In [115]:
data

array([[0.        , 0.40926864, 0.        , 0.89255626],
       [0.        , 0.31174478, 0.        , 1.2112391 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.74119466, 0.        , 1.29168528],
       [0.        , 0.        , 0.7411174 , 0.        ],
       [0.        , 1.2779262 , 1.68418952, 0.48085237],
       [0.577898  , 0.        , 0.        , 1.88829546]])

In [116]:
data[names != 'Joe'] = 7

In [117]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.31174478, 0.        , 1.2112391 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.2779262 , 1.68418952, 0.48085237],
       [0.577898  , 0.        , 0.        , 1.88829546]])

In [118]:
arr = np.empty((8, 4))

In [119]:
for i in range(8):
    arr[i] = i

In [120]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [121]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可

In [122]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

使用负数索引将会从末尾开始选取行

In [123]:
arr = np.arange(32).reshape((8, 4))

In [124]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [127]:
arr = np.arange(15).reshape((3, 5))

In [128]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

矩阵转秩

In [133]:
d = np.arange(10).reshape(2,5)

In [134]:
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [135]:
np.dot(d,d.T)

array([[ 30,  80],
       [ 80, 255]])

计算矩阵内积 在NumPy中，可以使用 numpy.dot 函数或者 @ 符号来计算矩阵的内积

In [136]:
arr = np.arange(16).reshape((2, 2, 4))

In [137]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [143]:
arr.transpose((1, 0, 2)) # 原数组副本

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）

In [139]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [140]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

swapaxes也是返回源数据的视图（不会进行任何复制操作）